services:
  app-blue:
    build:
      context: .
      dockerfile: Dockerfile
    image: jumoney-app:latest
    container_name: jumoney-app-blue
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      APP_COLOR: blue
    ports:
      - "3001:3000"
    networks:
      - jumoney-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  app-green:
    build:
      context: .
      dockerfile: Dockerfile
    image: jumoney-app:latest
    container_name: jumoney-app-green
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      APP_COLOR: green
    ports:
      - "3002:3000"
    networks:
      - jumoney-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  jumoney-net:
    driver: bridge
